"""Compile a skin YAML to canvas/src/data/skin.generated.ts.

Step 6/7 of TASK-13 (frontend skin loader). Next.js doesn't have great
runtime YAML loading — the canonical pattern is a build-time precompile
step that emits a typed TS const, then the canvas imports it normally.

Usage:
    venv-deploy-310/bin/python scripts/compile_skin.py --skin default
    venv-deploy-310/bin/python scripts/compile_skin.py --skin halliburton

The Makefile target ``use-skin`` wraps this and sets the env var.

Outputs:
    canvas/src/data/skin.generated.ts   — typed const, committed
    canvas/public/skin.json             — same data as JSON (for any runtime
                                          fetch that wants it; cheap to emit)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
SKINS_DIR = REPO_ROOT / "skins"
CANVAS_DATA_DIR = REPO_ROOT / "canvas" / "src" / "data"
CANVAS_PUBLIC_DIR = REPO_ROOT / "canvas" / "public"
SCHEMA_PATH = SKINS_DIR / "schema" / "customer.schema.json"


def _load_yaml(skin_slug: str) -> dict[str, Any]:
    yaml_path = SKINS_DIR / skin_slug / "customer.yaml"
    if not yaml_path.exists():
        raise FileNotFoundError(f"Skin not found: {yaml_path}")
    with yaml_path.open("r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Skin YAML must be a mapping at root: {yaml_path}")
    return data


def _validate(data: dict[str, Any]) -> None:
    """Validate against JSON Schema. Soft-fails if jsonschema isn't installed
    so the compile step doesn't block in minimal environments — the test
    suite is the authoritative gate."""
    try:
        import jsonschema  # type: ignore[import-not-found]
    except ImportError:
        print("  (jsonschema not installed; skipping validation)", file=sys.stderr)
        return
    with SCHEMA_PATH.open("r", encoding="utf-8") as f:
        schema = json.load(f)
    jsonschema.validate(data, schema)


def _emit_ts(data: dict[str, Any], skin_slug: str) -> str:
    """Emit the TS module. Hand-written templating instead of a full code
    generator — the schema is small and the output stays readable."""
    pretty = json.dumps(data, indent=2, ensure_ascii=False)
    return (
        "// AUTO-GENERATED by scripts/compile_skin.py. Do not edit by hand.\n"
        f"// Source: skins/{skin_slug}/customer.yaml\n"
        "//\n"
        "// Re-generate with:\n"
        f"//   make use-skin SKIN={skin_slug}\n"
        "// or:\n"
        f"//   venv-deploy-310/bin/python scripts/compile_skin.py --skin {skin_slug}\n"
        "\n"
        'import type { CustomerSkin } from "@/types/skin";\n'
        "\n"
        f"export const ACTIVE_SKIN_SLUG = {json.dumps(skin_slug)} as const;\n"
        "\n"
        f"export const ACTIVE_SKIN: CustomerSkin = {pretty} as const;\n"
        "\n"
        "export default ACTIVE_SKIN;\n"
    )


def compile_skin(skin_slug: str, *, write: bool = True) -> dict[str, Any]:
    """Compile one skin. Returns the parsed dict; writes TS + JSON to disk
    unless ``write=False`` (used by the test suite)."""
    print(f"Compiling skin: {skin_slug}")
    data = _load_yaml(skin_slug)
    _validate(data)

    if write:
        CANVAS_DATA_DIR.mkdir(parents=True, exist_ok=True)
        ts_out = CANVAS_DATA_DIR / "skin.generated.ts"
        ts_out.write_text(_emit_ts(data, skin_slug), encoding="utf-8")
        print(f"  wrote {ts_out.relative_to(REPO_ROOT)}")

        CANVAS_PUBLIC_DIR.mkdir(parents=True, exist_ok=True)
        json_out = CANVAS_PUBLIC_DIR / "skin.json"
        json_out.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        print(f"  wrote {json_out.relative_to(REPO_ROOT)}")

    customer_name = data.get("meta", {}).get("customer_display_name", skin_slug)
    persona_count = len(data.get("personas", []))
    print(f"  skin OK — {customer_name}, {persona_count} personas")
    return data


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--skin",
        default="default",
        help="Skin slug under skins/ (default: 'default').",
    )
    return p.parse_args()


def main() -> int:
    args = _parse_args()
    try:
        compile_skin(args.skin)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    except Exception as exc:  # noqa: BLE001 — top-level CLI
        print(f"ERROR compiling skin '{args.skin}': {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
