/**
 * Pre-baked A2UI v0.8 message payloads for the demo (TASK-45).
 *
 * The agent will eventually emit these dynamically — for v1 we ship
 * static samples so the canvas can demonstrate the A2UI-driven mode
 * without a live agent in the loop. Each payload was generated by the
 * Python emitter at `agents/utils/a2ui.py` (kc_drawer / cost_rollup
 * helpers); a future commit can replace these with live JSON streamed
 * from the orchestrator.
 *
 * v0.8 wraps `text` as `{literalString: "..."}` (a StringValue) and
 * Row/Column `children` as `{explicitList: [...]}` (a ComponentArrayRef).
 *
 * Schema reference:
 *   node_modules/@a2ui/web_core/src/v0_8/schemas/server_to_client_with_standard_catalog.json
 */

import type { ServerToClientMessage } from "@a2ui/react";

const txt = (s: string) => ({ literalString: s });
const childrenOf = (ids: string[]) => ({ explicitList: ids });

/** KC drawer for TX-007 / Tool X-V7 (Persona 3 cargo-plane scenario). */
export const KC_DRAWER_TX007: ServerToClientMessage[] = [
  {
    surfaceUpdate: {
      surfaceId: "kc-drawer",
      components: [
        { id: "title-eyebrow", component: { Text: { text: txt("Knowledge Catalog · canonical asset") } } },
        { id: "title", component: { Text: { text: txt("Tool X-V7  (TX-007)") } } },
        { id: "d1", component: { Divider: { axis: "horizontal" } } },
        { id: "aliases-h", component: { Text: { text: txt("Cross-system aliases") } } },
        { id: "alias-sap", component: { Text: { text: txt("SAP MATNR · MAT-67899") } } },
        { id: "alias-mxm", component: { Text: { text: txt("Maximo ITEMNUM · EQ-12399") } } },
        { id: "alias-fdp", component: { Text: { text: txt("FDP CONFIG · TX-CONFIG-V7") } } },
        { id: "d2", component: { Divider: { axis: "horizontal" } } },
        { id: "eq-h", component: { Text: { text: txt("Functional equivalents") } } },
        {
          id: "eq-0",
          component: {
            Text: {
              text: txt(
                "→ TX-001  (confidence 0.92)  · InTouch §3.2-2024  · gs://oilfield-services-unstructured/intouch_specs/uspto-10006249-B2.pdf",
              ),
            },
          },
        },
        { id: "d3", component: { Divider: { axis: "horizontal" } } },
        { id: "spec-h", component: { Text: { text: txt("Specification") } } },
        { id: "spec-mfr", component: { Text: { text: txt("Manufacturer · Schlumberger") } } },
        { id: "spec-yr", component: { Text: { text: txt("Introduced · 2021") } } },
        {
          id: "body",
          component: {
            Column: {
              children: childrenOf([
                "title-eyebrow",
                "title",
                "d1",
                "aliases-h",
                "alias-sap",
                "alias-mxm",
                "alias-fdp",
                "d2",
                "eq-h",
                "eq-0",
                "d3",
                "spec-h",
                "spec-mfr",
                "spec-yr",
              ]),
              distribution: "start",
              alignment: "stretch",
            },
          },
        },
        { id: "root", component: { Card: { child: "body" } } },
      ],
    },
  },
  { beginRendering: { surfaceId: "kc-drawer", root: "root" } },
];

/** Cost rollup banner for the cargo-plane scenario. */
export const COST_ROLLUP_CARGO_PLANE: ServerToClientMessage[] = [
  {
    surfaceUpdate: {
      surfaceId: "cost-rollup",
      components: [
        { id: "doomed-label", component: { Text: { text: txt("Naive baseline") } } },
        { id: "doomed-value", component: { Text: { text: txt("$420,000") } } },
        {
          id: "doomed",
          component: { Column: { children: childrenOf(["doomed-label", "doomed-value"]) } },
        },
        { id: "rec-label", component: { Text: { text: txt("Agent recommendation") } } },
        { id: "rec-value", component: { Text: { text: txt("$40,000") } } },
        {
          id: "rec",
          component: { Column: { children: childrenOf(["rec-label", "rec-value"]) } },
        },
        { id: "avoid-label", component: { Text: { text: txt("Avoided cost") } } },
        { id: "avoid-value", component: { Text: { text: txt("$380,000") } } },
        {
          id: "avoid",
          component: { Column: { children: childrenOf(["avoid-label", "avoid-value"]) } },
        },
        {
          id: "body",
          component: {
            Row: {
              children: childrenOf(["doomed", "rec", "avoid"]),
              distribution: "spaceBetween",
              alignment: "center",
            },
          },
        },
        { id: "root", component: { Card: { child: "body" } } },
      ],
    },
  },
  { beginRendering: { surfaceId: "cost-rollup", root: "root" } },
];
